### ISSUE TITLE
Strawberry Perl 5.24 Makefile.PL Builds Fail

### ISSUE THREAD

**Issue by theory** [theory/winperl-travis#1]
In 5.26, Strawberry Perl switched from `dmake` to `gmake`, and all works well. On 5.24, however, installation of `Makefile.PL`-based projects does not work. In theory, one can simply use `dmake` instead of `gmake`:

``` yaml
     - <<: *strawberry
      env: PERL_VERSION=5.24.4.1
      script:
        - perl Makefile.PL
        - dmake
        - dmake test
```

However, it won't even get this far if dependencies are `Makefile.PL`-based, as the CPAN::Test::Dummy::Perl5::Make module required this this project is, because the dependency installer (here modified to run with `-v`):

``` yaml
      install:
        - cpanm -v --notest --installdeps .
```

Fails, too, with [this error](https://travis-ci.com/theory/winperl-travis/jobs/170609614):

```
-MExtUtils::Command: C:Strawberryperlbinperl.exe: command not found
dmake.exe:  Error code 255, while making 'blib\lib\CPAN\Test\Dummy\Perl5\.exists'
```

@bingos says, "usually that means there is some other perl in the environment interferring. A UNIXy type perl, say a cygwin type perl." And indeed, the Travis CI Windows environment's [Chocolatey](https://chocolatey.org) (or [Git-Bash](https://gitforwindows.org)?) environment provides `/bin/perl`, which is [in the path](https://travis-ci.com/theory/winperl-travis/jobs/170646885). So maybe it needs to be removed from the path?
